/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package librarymanagementsystem;

import java.awt.Color;
import java.awt.Font;
import java.awt.Graphics2D;
import java.awt.RenderingHints;
import java.awt.image.BufferedImage;
import java.io.BufferedWriter;
import java.io.File;
import java.io.IOException;
import java.nio.charset.StandardCharsets;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import jdk.nashorn.internal.parser.TokenType;

/**
 *
 * @author Charith
 */
public class addBook extends javax.swing.JFrame {

    /**
     * Creates new form addBook
     */
    
    void saveImage(){
    File outputfile = new File("bookImages\\"+txtIsbn.getText()+".jpg");
            try {
                ImageIO.write(bi, "png", outputfile);
            } catch (IOException ex) {
                Logger.getLogger(bookSearchResult.class.getName()).log(Level.SEVERE, null, ex);
            }
    }
    
    public addBook() {
        initComponents();
    }

    public addBook(String uname, String user, String utype) {
        initComponents();
        this.uname = uname;
        this.user = user;
        this.utype = utype;
        userProfDet();
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btnUser = new javax.swing.JLabel();
        lblURname = new javax.swing.JLabel();
        lblUsername = new javax.swing.JLabel();
        btnExit = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        lblBookNauthor = new javax.swing.JLabel();
        lblISBN = new javax.swing.JLabel();
        lblBookStat = new javax.swing.JLabel();
        btnGoback = new javax.swing.JLabel();
        txtIsbn = new javax.swing.JTextField();
        txtBookName = new javax.swing.JTextField();
        txtBookAuthor = new javax.swing.JTextField();
        btnClear = new javax.swing.JLabel();
        btnRegister = new javax.swing.JLabel();
        btnUploadImage = new javax.swing.JLabel();
        imgBook = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1151, 657));
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(10, 13, 28));
        jPanel1.setLayout(null);

        btnUser.setIcon(new javax.swing.ImageIcon(getClass().getResource("/librarymanagementsystem/resources/profIco.png"))); // NOI18N
        btnUser.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnUserMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnUserMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnUserMouseExited(evt);
            }
        });
        jPanel1.add(btnUser);
        btnUser.setBounds(20, 20, 78, 78);

        lblURname.setFont(new java.awt.Font("Segoe UI Semilight", 0, 18)); // NOI18N
        lblURname.setForeground(new java.awt.Color(218, 219, 189));
        lblURname.setText("Jane Doe");
        lblURname.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblURnameMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblURnameMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblURnameMouseExited(evt);
            }
        });
        jPanel1.add(lblURname);
        lblURname.setBounds(100, 40, 600, 25);

        lblUsername.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N
        lblUsername.setForeground(new java.awt.Color(218, 219, 189));
        lblUsername.setText("janedoe12345");
        lblUsername.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblUsernameMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblUsernameMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblUsernameMouseExited(evt);
            }
        });
        jPanel1.add(lblUsername);
        lblUsername.setBounds(100, 60, 460, 20);

        btnExit.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnExit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/librarymanagementsystem/resources/icoExitD.png"))); // NOI18N
        btnExit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnExitMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnExitMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnExitMouseExited(evt);
            }
        });
        jPanel1.add(btnExit);
        btnExit.setBounds(1100, 10, 40, 40);

        jPanel2.setBackground(new java.awt.Color(10, 13, 28));
        jPanel2.setPreferredSize(new java.awt.Dimension(748, 526));

        lblBookNauthor.setFont(new java.awt.Font("Segoe UI Semilight", 0, 18)); // NOI18N
        lblBookNauthor.setForeground(new java.awt.Color(218, 219, 189));
        lblBookNauthor.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblBookNauthor.setText("ISBN");

        lblISBN.setFont(new java.awt.Font("Segoe UI Semilight", 0, 18)); // NOI18N
        lblISBN.setForeground(new java.awt.Color(218, 219, 189));
        lblISBN.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblISBN.setText("Book name");

        lblBookStat.setFont(new java.awt.Font("Segoe UI Semilight", 0, 18)); // NOI18N
        lblBookStat.setForeground(new java.awt.Color(218, 219, 189));
        lblBookStat.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblBookStat.setText("Author");

        btnGoback.setBackground(new java.awt.Color(218, 219, 189));
        btnGoback.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnGoback.setForeground(new java.awt.Color(10, 13, 28));
        btnGoback.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnGoback.setText("Go back");
        btnGoback.setOpaque(true);
        btnGoback.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnGobackMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnGobackMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnGobackMouseExited(evt);
            }
        });

        txtIsbn.setBackground(new java.awt.Color(10, 13, 28));
        txtIsbn.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txtIsbn.setForeground(new java.awt.Color(218, 219, 189));
        txtIsbn.setToolTipText("");
        txtIsbn.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(218, 219, 189), 1, true));
        txtIsbn.setMaximumSize(new java.awt.Dimension(90, 27));
        txtIsbn.setMinimumSize(new java.awt.Dimension(90, 27));
        txtIsbn.setPreferredSize(new java.awt.Dimension(90, 27));
        txtIsbn.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtIsbnFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtIsbnFocusLost(evt);
            }
        });
        txtIsbn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtIsbnActionPerformed(evt);
            }
        });

        txtBookName.setBackground(new java.awt.Color(10, 13, 28));
        txtBookName.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txtBookName.setForeground(new java.awt.Color(218, 219, 189));
        txtBookName.setToolTipText("");
        txtBookName.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(218, 219, 189), 1, true));
        txtBookName.setMaximumSize(new java.awt.Dimension(90, 27));
        txtBookName.setMinimumSize(new java.awt.Dimension(90, 27));
        txtBookName.setPreferredSize(new java.awt.Dimension(90, 27));
        txtBookName.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtBookNameFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtBookNameFocusLost(evt);
            }
        });
        txtBookName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtBookNameActionPerformed(evt);
            }
        });

        txtBookAuthor.setBackground(new java.awt.Color(10, 13, 28));
        txtBookAuthor.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txtBookAuthor.setForeground(new java.awt.Color(218, 219, 189));
        txtBookAuthor.setToolTipText("");
        txtBookAuthor.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(218, 219, 189), 1, true));
        txtBookAuthor.setMaximumSize(new java.awt.Dimension(90, 27));
        txtBookAuthor.setMinimumSize(new java.awt.Dimension(90, 27));
        txtBookAuthor.setPreferredSize(new java.awt.Dimension(90, 27));
        txtBookAuthor.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtBookAuthorFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtBookAuthorFocusLost(evt);
            }
        });
        txtBookAuthor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtBookAuthorActionPerformed(evt);
            }
        });

        btnClear.setBackground(new java.awt.Color(218, 219, 189));
        btnClear.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnClear.setForeground(new java.awt.Color(10, 13, 28));
        btnClear.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnClear.setText("Clear");
        btnClear.setOpaque(true);
        btnClear.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnClearMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnClearMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnClearMouseExited(evt);
            }
        });

        btnRegister.setBackground(new java.awt.Color(218, 219, 189));
        btnRegister.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnRegister.setForeground(new java.awt.Color(10, 13, 28));
        btnRegister.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnRegister.setText("Register");
        btnRegister.setOpaque(true);
        btnRegister.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnRegisterMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnRegisterMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnRegisterMouseExited(evt);
            }
        });

        btnUploadImage.setBackground(new java.awt.Color(218, 219, 189));
        btnUploadImage.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnUploadImage.setForeground(new java.awt.Color(10, 13, 28));
        btnUploadImage.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnUploadImage.setText("Add image");
        btnUploadImage.setOpaque(true);
        btnUploadImage.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnUploadImageMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnUploadImageMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnUploadImageMouseExited(evt);
            }
        });

        imgBook.setMaximumSize(new java.awt.Dimension(260, 350));
        imgBook.setMinimumSize(new java.awt.Dimension(260, 350));
        imgBook.setPreferredSize(new java.awt.Dimension(260, 350));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(imgBook, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(49, 49, 49)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(btnGoback, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 82, Short.MAX_VALUE)
                        .addComponent(btnClear, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(81, 81, 81)
                        .addComponent(btnRegister, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblISBN)
                            .addComponent(lblBookStat)
                            .addComponent(lblBookNauthor))
                        .addGap(60, 60, 60)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtBookAuthor, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 323, Short.MAX_VALUE)
                            .addComponent(txtBookName, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 323, Short.MAX_VALUE)
                            .addComponent(txtIsbn, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 323, Short.MAX_VALUE)))
                    .addComponent(btnUploadImage, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(118, 118, 118)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblBookNauthor)
                            .addComponent(txtIsbn, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(30, 30, 30)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblISBN)
                            .addComponent(txtBookName, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(31, 31, 31)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblBookStat)
                            .addComponent(txtBookAuthor, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(33, 33, 33)
                        .addComponent(btnUploadImage, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 44, Short.MAX_VALUE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnGoback, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnClear, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnRegister, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(imgBook, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(86, 86, 86))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 1151, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 1151, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnUserMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnUserMouseEntered
        // TODO add your handling code here:
        userProfHover();
    }//GEN-LAST:event_btnUserMouseEntered

    private void btnUserMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnUserMouseExited
        // TODO add your handling code here:
        userProfExit();
    }//GEN-LAST:event_btnUserMouseExited

    private void lblURnameMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblURnameMouseEntered
        // TODO add your handling code here:
        userProfHover();
    }//GEN-LAST:event_lblURnameMouseEntered

    private void lblURnameMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblURnameMouseExited
        // TODO add your handling code here:
        userProfExit();
    }//GEN-LAST:event_lblURnameMouseExited

    private void lblUsernameMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblUsernameMouseEntered
        // TODO add your handling code here:
        userProfHover();
    }//GEN-LAST:event_lblUsernameMouseEntered

    private void lblUsernameMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblUsernameMouseExited
        // TODO add your handling code here:
        userProfExit();
    }//GEN-LAST:event_lblUsernameMouseExited

    private void btnExitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnExitMouseClicked
        // TODO add your handling code here:
        int res = JOptionPane.showConfirmDialog(null,"Are you sure you want to Logout?","Logout?",JOptionPane.YES_NO_OPTION,JOptionPane.QUESTION_MESSAGE);
        if(res==0){
            login lf = new login();
            this.dispose();
            lf.show();
        }
    }//GEN-LAST:event_btnExitMouseClicked

    private void btnExitMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnExitMouseEntered
        // TODO add your handling code here:
        exitIconL.getImage().flush();
        btnExit.setIcon(exitIconL);
    }//GEN-LAST:event_btnExitMouseEntered

    private void btnExitMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnExitMouseExited
        // TODO add your handling code here:
        exitIconL.getImage().flush();
        btnExit.setIcon(exitIconD);
    }//GEN-LAST:event_btnExitMouseExited

    private void btnGobackMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnGobackMouseClicked
        // TODO add your handling code here:
        admindashboard df = new admindashboard(uname, user, utype);
        df.show();
        this.dispose();
    }//GEN-LAST:event_btnGobackMouseClicked

    private void btnGobackMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnGobackMouseEntered
        // TODO add your handling code here:
        Font boldFont = new Font(btnGoback.getFont().getName(),Font.PLAIN,btnGoback.getFont().getSize());
        btnGoback.setFont(boldFont);

        btnGoback.setBackground(new Color(240, 240, 228));
    }//GEN-LAST:event_btnGobackMouseEntered

    private void btnGobackMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnGobackMouseExited
        // TODO add your handling code here:
        Font boldFont = new Font(btnGoback.getFont().getName(),Font.PLAIN,btnGoback.getFont().getSize());
        btnGoback.setFont(boldFont);

        btnGoback.setBackground(new Color(218, 219, 189));
    }//GEN-LAST:event_btnGobackMouseExited

    private void txtIsbnFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtIsbnFocusGained
        // remove placeholder text
        txtIsbn.setForeground(Color.WHITE);
    }//GEN-LAST:event_txtIsbnFocusGained

    private void txtIsbnFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtIsbnFocusLost
        // add placeholder text
        txtIsbn.setForeground(new Color(218, 219, 189));
    }//GEN-LAST:event_txtIsbnFocusLost

    private void txtIsbnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtIsbnActionPerformed
        // TODO add your handling code here:
        txtBookName.requestFocus();
    }//GEN-LAST:event_txtIsbnActionPerformed

    private void txtBookNameFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtBookNameFocusGained
        // TODO add your handling code here:
        txtBookName.setForeground(Color.WHITE);
    }//GEN-LAST:event_txtBookNameFocusGained

    private void txtBookNameFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtBookNameFocusLost
        // TODO add your handling code here:
        txtBookName.setForeground(new Color(218, 219, 189));
    }//GEN-LAST:event_txtBookNameFocusLost

    private void txtBookNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtBookNameActionPerformed
        // TODO add your handling code here:
        txtBookAuthor.requestFocus();
    }//GEN-LAST:event_txtBookNameActionPerformed

    private void txtBookAuthorFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtBookAuthorFocusGained
        // TODO add your handling code here:
        txtBookAuthor.setForeground(Color.WHITE);
    }//GEN-LAST:event_txtBookAuthorFocusGained

    private void txtBookAuthorFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtBookAuthorFocusLost
        // TODO add your handling code here:
        txtBookAuthor.setForeground(new Color(218, 219, 189));
    }//GEN-LAST:event_txtBookAuthorFocusLost

    private void txtBookAuthorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtBookAuthorActionPerformed
        // TODO add your handling code here:
        btnRegister.requestFocus();
    }//GEN-LAST:event_txtBookAuthorActionPerformed

    private void btnClearMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnClearMouseClicked
        // TODO add your handling code here:
        clear();
    }//GEN-LAST:event_btnClearMouseClicked

    void clear()
    {
        txtBookAuthor.setText("");
        txtBookName.setText("");
        txtIsbn.setText("");
    }
    
    private void btnClearMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnClearMouseEntered
        // TODO add your handling code here:
        Font boldFont = new Font(btnClear.getFont().getName(),Font.PLAIN,btnClear.getFont().getSize());
        btnClear.setFont(boldFont);

        btnClear.setBackground(new Color(240, 240, 228));
    }//GEN-LAST:event_btnClearMouseEntered

    private void btnClearMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnClearMouseExited
        // TODO add your handling code here:
        Font boldFont = new Font(btnClear.getFont().getName(),Font.PLAIN,btnClear.getFont().getSize());
        btnClear.setFont(boldFont);

        btnClear.setBackground(new Color(218, 219, 189));
    }//GEN-LAST:event_btnClearMouseExited

    
    private void btnRegisterMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnRegisterMouseClicked
        // TODO add your handling code here:
        if(txtIsbn.getText().equals("") || txtBookName.getText().equals(""))
        {
            JOptionPane.showMessageDialog(this, "Please fill all text fields" + "\n","Fill all fields!", JOptionPane.INFORMATION_MESSAGE);
        }
        else if((txtIsbn.getText().length() != 13) && (txtIsbn.getText().length() != 10))
        {
            JOptionPane.showMessageDialog(this, "ISBN should be 10 or 13 numbers" + "\n","check ISBN", JOptionPane.INFORMATION_MESSAGE);
        }
        else
        {
            try {
                Connection conn = null;
                Class.forName("java.sql.Driver");
                conn = DriverManager.getConnection("jdbc:mysql://localhost/librarymanagementsystem?useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC", "root", "");
                if (conn != null) {
                    String addBookQ = "INSERT INTO book (ISBNnumber, bookName, authorName,currentAvailability,admUsername) VALUES (?,?,?,?,?)";
                    PreparedStatement ps = conn.prepareCall(addBookQ);
                    ps.setString(1, txtIsbn.getText());
                    ps.setString(2, txtBookName.getText());
                    ps.setString(3, txtBookAuthor.getText());
                    ps.setString(4, "Available");
                    ps.setString(5, user);
                    ps.execute();
                    JOptionPane.showMessageDialog(this, "Book " + txtIsbn.getText() + " was Successfully Registered to the System!", "REGISTERED!", JOptionPane.INFORMATION_MESSAGE);
                    ps.close();
                    conn.close();
                    saveImage();
                    imgBook.setIcon(null);
                    clear();
                }
            } catch (Exception ex) {
                JOptionPane.showMessageDialog(null, "Database connectivity is NOT successful...." + "\n" + ex);
            }  
        }
    }//GEN-LAST:event_btnRegisterMouseClicked

    private void btnRegisterMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnRegisterMouseEntered
        // TODO add your handling code here:
        Font boldFont = new Font(btnRegister.getFont().getName(),Font.PLAIN,btnRegister.getFont().getSize());
        btnRegister.setFont(boldFont);

        btnRegister.setBackground(new Color(240, 240, 228));
    }//GEN-LAST:event_btnRegisterMouseEntered

    private void btnRegisterMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnRegisterMouseExited
        // TODO add your handling code here:
        Font boldFont = new Font(btnRegister.getFont().getName(),Font.PLAIN,btnRegister.getFont().getSize());
        btnRegister.setFont(boldFont);

        btnRegister.setBackground(new Color(218, 219, 189));
    }//GEN-LAST:event_btnRegisterMouseExited

    private void btnUserMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnUserMouseClicked
        // TODO add your handling code here:
        userProf();
    }//GEN-LAST:event_btnUserMouseClicked

    private void lblURnameMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblURnameMouseClicked
        // TODO add your handling code here:
        userProf();
    }//GEN-LAST:event_lblURnameMouseClicked

    private void lblUsernameMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblUsernameMouseClicked
        // TODO add your handling code here:
        userProf();
    }//GEN-LAST:event_lblUsernameMouseClicked

    private void btnUploadImageMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnUploadImageMouseClicked
        // TODO add your handling code here:
        JFileChooser chooser = new JFileChooser();
        chooser.showOpenDialog(null);
        File f;
        f = chooser.getSelectedFile();

        String filename = f.getAbsolutePath();
        System.out.println(filename);
        try {
            ImageIcon ii=new ImageIcon(scaleImage(260, 350, ImageIO.read(new File(f.getAbsolutePath()))));//get the image from file chooser and scale it to match JLabel size
            imgBook.setIcon(ii);
        } catch (Exception ex) {
            ex.printStackTrace();
        }
    }//GEN-LAST:event_btnUploadImageMouseClicked

    private void btnUploadImageMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnUploadImageMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_btnUploadImageMouseEntered

    private void btnUploadImageMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnUploadImageMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_btnUploadImageMouseExited

    static BufferedImage bi;
    
    public static BufferedImage scaleImage(int w, int h, BufferedImage img) throws Exception {
        bi = new BufferedImage(w, h, BufferedImage.TRANSLUCENT);
        Graphics2D g2d = (Graphics2D) bi.createGraphics();
        g2d.setRenderingHint(RenderingHints.KEY_ANTIALIASING, RenderingHints.VALUE_ANTIALIAS_ON);
        g2d.addRenderingHints(new RenderingHints(RenderingHints.KEY_RENDERING, RenderingHints.VALUE_RENDER_QUALITY));
        g2d.drawImage(img, 0, 0, w, h, null);
        g2d.dispose();
        return bi;
    }
    
    void userProf()
    {
        userProfile uf = new userProfile(uname, user, utype);
        uf.show();
        this.dispose();
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(addBook.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(addBook.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(addBook.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(addBook.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new addBook().setVisible(true);
            }
        });
    }
        
    String uname = "";
    String user = "";
    String utype = "";
    
    private void userProfDet()
    {
        lblURname.setText(uname);
        lblUsername.setText(user);
    }
    
    String exitIconLPath = "src\\librarymanagementsystem\\resources\\icoExitL.png";
    ImageIcon exitIconL = new ImageIcon(exitIconLPath);
    
    String exitIconDPath = "src\\librarymanagementsystem\\resources\\icoExitD.png";
    ImageIcon exitIconD = new ImageIcon(exitIconDPath);
    
    String proIcoLPath = "src\\librarymanagementsystem\\resources\\proIcoL.png";
    ImageIcon proIcoL = new ImageIcon(proIcoLPath);
    
    String proIcoDPath = "src\\librarymanagementsystem\\resources\\profIco.png";
    ImageIcon proIcoD = new ImageIcon(proIcoDPath);
    
    
    void userProfHover()
    {
        lblURname.setForeground(Color.white);
        lblUsername.setForeground(Color.white);
        proIcoL.getImage().flush();
        btnUser.setIcon(proIcoL);
    }
    
    void userProfExit()
    {
        lblURname.setForeground(new Color(218, 219, 189));
        lblUsername.setForeground(new Color(218, 219, 189));
        proIcoD.getImage().flush();
        btnUser.setIcon(proIcoD);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel btnClear;
    private javax.swing.JLabel btnExit;
    private javax.swing.JLabel btnGoback;
    private javax.swing.JLabel btnRegister;
    private javax.swing.JLabel btnUploadImage;
    private javax.swing.JLabel btnUser;
    private javax.swing.JLabel imgBook;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel lblBookNauthor;
    private javax.swing.JLabel lblBookStat;
    private javax.swing.JLabel lblISBN;
    private javax.swing.JLabel lblURname;
    private javax.swing.JLabel lblUsername;
    private javax.swing.JTextField txtBookAuthor;
    private javax.swing.JTextField txtBookName;
    private javax.swing.JTextField txtIsbn;
    // End of variables declaration//GEN-END:variables
}
