/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package librarymanagementsystem;

import java.awt.Color;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author Charith
 */
public class admindashboard extends javax.swing.JFrame {

    /**
     * Creates new form admindashboard
     */
    public admindashboard() {
        initComponents();
    }
    
    admindashboard(String uname, String user, String utype) {
        initComponents();
        this.uname = uname;
        this.user = user;
        this.utype = utype;
        userProfDet();
    }
    
    String uname = "";
    String user = "";
    String utype = "";
    
    private void userProfDet()
    {
        lblURname.setText(uname);
        lblUsername.setText(user);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btnUser = new javax.swing.JLabel();
        lblURname = new javax.swing.JLabel();
        lblUsername = new javax.swing.JLabel();
        btnExit = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        btnAddBooks = new javax.swing.JLabel();
        btnDisBooks = new javax.swing.JLabel();
        btnIssBook = new javax.swing.JLabel();
        btnRetBook = new javax.swing.JLabel();
        btnSearchBook = new javax.swing.JLabel();
        btnStaff = new javax.swing.JLabel();
        btnMember = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(1151, 657));
        setMinimumSize(new java.awt.Dimension(1151, 657));
        setUndecorated(true);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(10, 13, 28));
        jPanel1.setLayout(null);

        btnUser.setIcon(new javax.swing.ImageIcon(getClass().getResource("/librarymanagementsystem/resources/profIco.png"))); // NOI18N
        btnUser.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnUserMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnUserMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnUserMouseExited(evt);
            }
        });
        jPanel1.add(btnUser);
        btnUser.setBounds(20, 20, 78, 78);

        lblURname.setFont(new java.awt.Font("Segoe UI Semilight", 0, 18)); // NOI18N
        lblURname.setForeground(new java.awt.Color(218, 219, 189));
        lblURname.setText("Jane Doe");
        lblURname.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblURnameMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblURnameMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblURnameMouseExited(evt);
            }
        });
        jPanel1.add(lblURname);
        lblURname.setBounds(100, 40, 600, 25);

        lblUsername.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N
        lblUsername.setForeground(new java.awt.Color(218, 219, 189));
        lblUsername.setText("janedoe12345");
        lblUsername.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblUsernameMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblUsernameMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblUsernameMouseExited(evt);
            }
        });
        jPanel1.add(lblUsername);
        lblUsername.setBounds(100, 60, 460, 20);

        btnExit.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnExit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/librarymanagementsystem/resources/icoExitD.png"))); // NOI18N
        btnExit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnExitMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnExitMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnExitMouseExited(evt);
            }
        });
        jPanel1.add(btnExit);
        btnExit.setBounds(1100, 10, 40, 40);

        jPanel2.setBackground(new java.awt.Color(10, 13, 28));
        jPanel2.setForeground(new java.awt.Color(218, 219, 189));

        btnAddBooks.setBackground(new java.awt.Color(218, 219, 189));
        btnAddBooks.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnAddBooks.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnAddBooks.setIcon(new javax.swing.ImageIcon(getClass().getResource("/librarymanagementsystem/resources/addBooks.png"))); // NOI18N
        btnAddBooks.setText("Add books");
        btnAddBooks.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnAddBooks.setMaximumSize(new java.awt.Dimension(89, 115));
        btnAddBooks.setMinimumSize(new java.awt.Dimension(89, 115));
        btnAddBooks.setOpaque(true);
        btnAddBooks.setPreferredSize(new java.awt.Dimension(89, 115));
        btnAddBooks.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnAddBooks.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnAddBooksMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnAddBooksMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnAddBooksMouseExited(evt);
            }
        });

        btnDisBooks.setBackground(new java.awt.Color(218, 219, 189));
        btnDisBooks.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnDisBooks.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnDisBooks.setIcon(new javax.swing.ImageIcon(getClass().getResource("/librarymanagementsystem/resources/disBooks.png"))); // NOI18N
        btnDisBooks.setText("Dispose books");
        btnDisBooks.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnDisBooks.setMaximumSize(new java.awt.Dimension(89, 115));
        btnDisBooks.setMinimumSize(new java.awt.Dimension(89, 115));
        btnDisBooks.setOpaque(true);
        btnDisBooks.setPreferredSize(new java.awt.Dimension(89, 115));
        btnDisBooks.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnDisBooks.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnDisBooksMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnDisBooksMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnDisBooksMouseExited(evt);
            }
        });

        btnIssBook.setBackground(new java.awt.Color(218, 219, 189));
        btnIssBook.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnIssBook.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnIssBook.setIcon(new javax.swing.ImageIcon(getClass().getResource("/librarymanagementsystem/resources/issueBooks.png"))); // NOI18N
        btnIssBook.setText("Issue books");
        btnIssBook.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnIssBook.setIconTextGap(16);
        btnIssBook.setMaximumSize(new java.awt.Dimension(89, 115));
        btnIssBook.setMinimumSize(new java.awt.Dimension(89, 115));
        btnIssBook.setOpaque(true);
        btnIssBook.setPreferredSize(new java.awt.Dimension(89, 115));
        btnIssBook.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnIssBook.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnIssBookMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnIssBookMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnIssBookMouseExited(evt);
            }
        });

        btnRetBook.setBackground(new java.awt.Color(218, 219, 189));
        btnRetBook.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnRetBook.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnRetBook.setIcon(new javax.swing.ImageIcon(getClass().getResource("/librarymanagementsystem/resources/returnBook.png"))); // NOI18N
        btnRetBook.setText("Return books");
        btnRetBook.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnRetBook.setIconTextGap(16);
        btnRetBook.setMaximumSize(new java.awt.Dimension(89, 115));
        btnRetBook.setMinimumSize(new java.awt.Dimension(89, 115));
        btnRetBook.setOpaque(true);
        btnRetBook.setPreferredSize(new java.awt.Dimension(89, 115));
        btnRetBook.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnRetBook.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnRetBookMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnRetBookMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnRetBookMouseExited(evt);
            }
        });

        btnSearchBook.setBackground(new java.awt.Color(218, 219, 189));
        btnSearchBook.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnSearchBook.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnSearchBook.setIcon(new javax.swing.ImageIcon(getClass().getResource("/librarymanagementsystem/resources/searchBooks.png"))); // NOI18N
        btnSearchBook.setText("Search books");
        btnSearchBook.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnSearchBook.setIconTextGap(16);
        btnSearchBook.setMaximumSize(new java.awt.Dimension(89, 115));
        btnSearchBook.setMinimumSize(new java.awt.Dimension(89, 115));
        btnSearchBook.setOpaque(true);
        btnSearchBook.setPreferredSize(new java.awt.Dimension(89, 115));
        btnSearchBook.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnSearchBook.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnSearchBookMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnSearchBookMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnSearchBookMouseExited(evt);
            }
        });

        btnStaff.setBackground(new java.awt.Color(218, 219, 189));
        btnStaff.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnStaff.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnStaff.setIcon(new javax.swing.ImageIcon(getClass().getResource("/librarymanagementsystem/resources/staffD.png"))); // NOI18N
        btnStaff.setText("Staff");
        btnStaff.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnStaff.setIconTextGap(16);
        btnStaff.setMaximumSize(new java.awt.Dimension(89, 115));
        btnStaff.setMinimumSize(new java.awt.Dimension(89, 115));
        btnStaff.setOpaque(true);
        btnStaff.setPreferredSize(new java.awt.Dimension(89, 115));
        btnStaff.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnStaff.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnStaffMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnStaffMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnStaffMouseExited(evt);
            }
        });

        btnMember.setBackground(new java.awt.Color(218, 219, 189));
        btnMember.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnMember.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnMember.setIcon(new javax.swing.ImageIcon(getClass().getResource("/librarymanagementsystem/resources/member.png"))); // NOI18N
        btnMember.setText("Members");
        btnMember.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnMember.setIconTextGap(16);
        btnMember.setMaximumSize(new java.awt.Dimension(89, 115));
        btnMember.setMinimumSize(new java.awt.Dimension(89, 115));
        btnMember.setOpaque(true);
        btnMember.setPreferredSize(new java.awt.Dimension(89, 115));
        btnMember.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnMember.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnMemberMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnMemberMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnMemberMouseExited(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(111, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(btnAddBooks, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(120, 120, 120)
                        .addComponent(btnDisBooks, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(btnSearchBook, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(120, 120, 120)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnIssBook, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnMember, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(120, 120, 120)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnRetBook, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnStaff, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(108, 108, 108))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnRetBook, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnDisBooks, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnIssBook, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAddBooks, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 106, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnMember, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnStaff, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSearchBook, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(85, 85, 85))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    String exitIconLPath = "src\\librarymanagementsystem\\resources\\icoExitL.png";
    ImageIcon exitIconL = new ImageIcon(exitIconLPath);
    
    String exitIconDPath = "src\\librarymanagementsystem\\resources\\icoExitD.png";
    ImageIcon exitIconD = new ImageIcon(exitIconDPath);
    
    String proIcoLPath = "src\\librarymanagementsystem\\resources\\proIcoL.png";
    ImageIcon proIcoL = new ImageIcon(proIcoLPath);
    
    String proIcoDPath = "src\\librarymanagementsystem\\resources\\profIco.png";
    ImageIcon proIcoD = new ImageIcon(proIcoDPath);
    
    
    void userProfHover()
    {
        lblURname.setForeground(Color.white);
        lblUsername.setForeground(Color.white);
        proIcoL.getImage().flush();
        btnUser.setIcon(proIcoL);
    }
    
    void userProfExit()
    {
        lblURname.setForeground(new Color(218, 219, 189));
        lblUsername.setForeground(new Color(218, 219, 189));
        proIcoD.getImage().flush();
        btnUser.setIcon(proIcoD);
    }
    
    private void btnUserMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnUserMouseEntered
        // TODO add your handling code here:
        userProfHover();
    }//GEN-LAST:event_btnUserMouseEntered

    private void btnUserMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnUserMouseExited
        // TODO add your handling code here:
        userProfExit();
    }//GEN-LAST:event_btnUserMouseExited

    private void lblURnameMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblURnameMouseEntered
        // TODO add your handling code here:
        userProfHover();
    }//GEN-LAST:event_lblURnameMouseEntered

    private void lblURnameMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblURnameMouseExited
        // TODO add your handling code here:
        userProfExit();
    }//GEN-LAST:event_lblURnameMouseExited

    private void lblUsernameMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblUsernameMouseEntered
        // TODO add your handling code here:
        userProfHover();
    }//GEN-LAST:event_lblUsernameMouseEntered

    private void lblUsernameMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblUsernameMouseExited
        // TODO add your handling code here:
        userProfExit();
    }//GEN-LAST:event_lblUsernameMouseExited

    private void btnExitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnExitMouseClicked
        // TODO add your handling code here:
        int res = JOptionPane.showConfirmDialog(null,"Are you sure you want to Logout?","Logout?",JOptionPane.YES_NO_OPTION,JOptionPane.QUESTION_MESSAGE);
        if(res==0){
            login lf = new login();
            this.dispose();
            lf.show();
        }
    }//GEN-LAST:event_btnExitMouseClicked

    private void btnExitMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnExitMouseEntered
        // TODO add your handling code here:
        exitIconL.getImage().flush();
        btnExit.setIcon(exitIconL);
    }//GEN-LAST:event_btnExitMouseEntered

    private void btnExitMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnExitMouseExited
        // TODO add your handling code here:
        exitIconL.getImage().flush();
        btnExit.setIcon(exitIconD);
    }//GEN-LAST:event_btnExitMouseExited

    private void btnAddBooksMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAddBooksMouseEntered
        // TODO add your handling code here:
        btnAddBooks.setBackground(new Color(240, 240, 228));
    }//GEN-LAST:event_btnAddBooksMouseEntered

    private void btnAddBooksMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAddBooksMouseExited
        // TODO add your handling code here:
        btnAddBooks.setBackground(new Color(218, 219, 189));
    }//GEN-LAST:event_btnAddBooksMouseExited

    private void btnDisBooksMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnDisBooksMouseEntered
        // TODO add your handling code here:
        btnDisBooks.setBackground(new Color(240, 240, 228));
    }//GEN-LAST:event_btnDisBooksMouseEntered

    private void btnDisBooksMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnDisBooksMouseExited
        // TODO add your handling code here:
        btnDisBooks.setBackground(new Color(218, 219, 189));
    }//GEN-LAST:event_btnDisBooksMouseExited

    private void btnIssBookMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnIssBookMouseEntered
        // TODO add your handling code here:
        btnIssBook.setBackground(new Color(240, 240, 228));
    }//GEN-LAST:event_btnIssBookMouseEntered

    private void btnIssBookMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnIssBookMouseExited
        // TODO add your handling code here:
        btnIssBook.setBackground(new Color(218, 219, 189));
    }//GEN-LAST:event_btnIssBookMouseExited

    private void btnRetBookMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnRetBookMouseEntered
        // TODO add your handling code here:
        btnRetBook.setBackground(new Color(240, 240, 228));
    }//GEN-LAST:event_btnRetBookMouseEntered

    private void btnRetBookMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnRetBookMouseExited
        // TODO add your handling code here:
        btnRetBook.setBackground(new Color(218, 219, 189));
    }//GEN-LAST:event_btnRetBookMouseExited

    private void btnSearchBookMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSearchBookMouseEntered
        // TODO add your handling code here:
        btnSearchBook.setBackground(new Color(240, 240, 228));
    }//GEN-LAST:event_btnSearchBookMouseEntered

    private void btnSearchBookMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSearchBookMouseExited
        // TODO add your handling code here:
        btnSearchBook.setBackground(new Color(218, 219, 189));
    }//GEN-LAST:event_btnSearchBookMouseExited

    private void btnStaffMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnStaffMouseEntered
        // TODO add your handling code here:
        staffL.getImage().flush();
        btnStaff.setIcon(staffL);
        btnStaff.setBackground(new Color(240, 240, 228));
    }//GEN-LAST:event_btnStaffMouseEntered

    private void btnStaffMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnStaffMouseExited
        // TODO add your handling code here:
        staffD.getImage().flush();
        btnStaff.setIcon(staffD);
        btnStaff.setBackground(new Color(218, 219, 189));
    }//GEN-LAST:event_btnStaffMouseExited

    private void btnMemberMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnMemberMouseEntered
        // TODO add your handling code here:
        btnMember.setBackground(new Color(240, 240, 228));
    }//GEN-LAST:event_btnMemberMouseEntered

    private void btnMemberMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnMemberMouseExited
        // TODO add your handling code here:
        btnMember.setBackground(new Color(218, 219, 189));
    }//GEN-LAST:event_btnMemberMouseExited

    private void btnSearchBookMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSearchBookMouseClicked
        // TODO add your handling code here:
        dashboard df = new dashboard(uname, user, utype);
        df.show();
        this.dispose();
    }//GEN-LAST:event_btnSearchBookMouseClicked

    private void btnAddBooksMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAddBooksMouseClicked
        // TODO add your handling code here:
        addBook df = new addBook(uname, user, utype);
        df.show();
        this.dispose();
    }//GEN-LAST:event_btnAddBooksMouseClicked

    private void btnMemberMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnMemberMouseClicked
        // TODO add your handling code here:
        addMember df = new addMember(uname, user, utype, "Member");
        df.show();
        this.dispose();
    }//GEN-LAST:event_btnMemberMouseClicked

    private void btnStaffMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnStaffMouseClicked
        // TODO add your handling code here:
        addMember df = new addMember(uname, user, utype, "Admin");
        df.show();
        this.dispose();
    }//GEN-LAST:event_btnStaffMouseClicked

    private void btnDisBooksMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnDisBooksMouseClicked
        // TODO add your handling code here:
        disposeBook df = new disposeBook(uname, user, utype);
        df.show();
        this.dispose();
    }//GEN-LAST:event_btnDisBooksMouseClicked

    private void btnUserMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnUserMouseClicked
        // TODO add your handling code here:
        userProf();
    }//GEN-LAST:event_btnUserMouseClicked

    private void lblURnameMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblURnameMouseClicked
        // TODO add your handling code here:
        userProf();
    }//GEN-LAST:event_lblURnameMouseClicked

    private void lblUsernameMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblUsernameMouseClicked
        // TODO add your handling code here:
        userProf();
    }//GEN-LAST:event_lblUsernameMouseClicked

    void userProf()
    {
        userProfile uf = new userProfile(uname, user, utype);
        uf.show();
        this.dispose();
    }
    
    private void btnIssBookMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnIssBookMouseClicked
        // TODO add your handling code here:
        issueBook uf = new issueBook(uname, user, utype);
        uf.show();
        this.dispose();
    }//GEN-LAST:event_btnIssBookMouseClicked

    private void btnRetBookMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnRetBookMouseClicked
        // TODO add your handling code here:
        returnBook uf = new returnBook(uname, user, utype);
        uf.show();
        this.dispose();
    }//GEN-LAST:event_btnRetBookMouseClicked

    String pathStaffL = "src\\librarymanagementsystem\\resources\\staffL.png";
    ImageIcon staffL = new ImageIcon(pathStaffL);
    
    String pathStaffD = "src\\librarymanagementsystem\\resources\\staffD.png";
    ImageIcon staffD = new ImageIcon(pathStaffD);
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(admindashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(admindashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(admindashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(admindashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new admindashboard().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel btnAddBooks;
    private javax.swing.JLabel btnDisBooks;
    private javax.swing.JLabel btnExit;
    private javax.swing.JLabel btnIssBook;
    private javax.swing.JLabel btnMember;
    private javax.swing.JLabel btnRetBook;
    private javax.swing.JLabel btnSearchBook;
    private javax.swing.JLabel btnStaff;
    private javax.swing.JLabel btnUser;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel lblURname;
    private javax.swing.JLabel lblUsername;
    // End of variables declaration//GEN-END:variables
}
