/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package librarymanagementsystem;

import java.awt.Color;
import java.awt.Font;
import java.awt.Graphics2D;
import java.awt.Image;
import java.awt.RenderingHints;
import java.awt.image.BufferedImage;
import java.io.BufferedWriter;
import java.io.File;
import java.io.IOException;
import java.nio.charset.StandardCharsets;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import jdk.nashorn.internal.parser.TokenType;

/**
 *
 * @author Charith
 */
public class bookSearchResult extends javax.swing.JFrame {

    /**
     * Creates new form bookSearchResult
     */
    String uname = "";
    String user = "";
    String utype = "";
    String isbn = "";
    String bookName = "";
    String bookAuthor = "";
    String currentAv = "";

    public bookSearchResult() {
        initComponents();
    }

    bookSearchResult(String uname, String user, String utype, String isbn, String bookName, String bookAuthor, String currentAv) {
        initComponents();
        this.isbn = isbn;
        this.bookName = bookName;
        this.bookAuthor = bookAuthor;
        this.currentAv = currentAv;
        this.uname = uname;
        this.user = user;
        this.utype = utype;
        bookDetails();
        userProfDet();
        try {
            openBookIamge(isbn);
        } catch (Exception ex) {
            Logger.getLogger(bookSearchResult.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    void userProf()
    {
        userProfile uf = new userProfile(uname, user, utype);
        uf.show();
        this.dispose();
    }
    
    private void userProfDet() {
        lblURname.setText(uname);
        lblUsername.setText(user);
    }

    private void bookDetails() {
        lblBookNauthor.setText(bookName + " - " + bookAuthor);
        lblISBN.setText("ISBN: " + isbn);
        lblBookStat.setText("Book status: " + currentAv);
    }

    String exitIconLPath = "src\\librarymanagementsystem\\resources\\icoExitL.png";
    ImageIcon exitIconL = new ImageIcon(exitIconLPath);

    String exitIconDPath = "src\\librarymanagementsystem\\resources\\icoExitD.png";
    ImageIcon exitIconD = new ImageIcon(exitIconDPath);

    String proIcoLPath = "src\\librarymanagementsystem\\resources\\proIcoL.png";
    ImageIcon proIcoL = new ImageIcon(proIcoLPath);

    String proIcoDPath = "src\\librarymanagementsystem\\resources\\profIco.png";
    ImageIcon proIcoD = new ImageIcon(proIcoDPath);

    void userProfHover() {
        lblURname.setForeground(Color.white);
        lblUsername.setForeground(Color.white);
        proIcoL.getImage().flush();
        btnUser.setIcon(proIcoL);
    }

    void userProfExit() {
        lblURname.setForeground(new Color(218, 219, 189));
        lblUsername.setForeground(new Color(218, 219, 189));
        proIcoD.getImage().flush();
        btnUser.setIcon(proIcoD);
    }

    void openBookIamge(String isbn) throws Exception {
        this.isbn = isbn;
        try {
            ImageIcon bookImage = new ImageIcon(scaleImage(260, 350, ImageIO.read((new File("bookImages\\" + isbn + ".jpg")))));
            imgBook.setIcon(bookImage);
        } catch (IOException e) {
            String workingDir = System.getProperty("user.dir");
            System.out.println("Current working directory : " + workingDir);
            e.printStackTrace();
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btnUser = new javax.swing.JLabel();
        lblURname = new javax.swing.JLabel();
        lblUsername = new javax.swing.JLabel();
        btnExit = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        lblBookNauthor = new javax.swing.JLabel();
        lblISBN = new javax.swing.JLabel();
        lblBookStat = new javax.swing.JLabel();
        btnGoback = new javax.swing.JLabel();
        imgBook = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1151, 657));
        setUndecorated(true);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(10, 13, 28));
        jPanel1.setLayout(null);

        btnUser.setIcon(new javax.swing.ImageIcon(getClass().getResource("/librarymanagementsystem/resources/profIco.png"))); // NOI18N
        btnUser.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnUserMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnUserMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnUserMouseExited(evt);
            }
        });
        jPanel1.add(btnUser);
        btnUser.setBounds(20, 20, 78, 78);

        lblURname.setFont(new java.awt.Font("Segoe UI Semilight", 0, 18)); // NOI18N
        lblURname.setForeground(new java.awt.Color(218, 219, 189));
        lblURname.setText("Jane Doe");
        lblURname.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblURnameMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblURnameMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblURnameMouseExited(evt);
            }
        });
        jPanel1.add(lblURname);
        lblURname.setBounds(100, 40, 600, 25);

        lblUsername.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N
        lblUsername.setForeground(new java.awt.Color(218, 219, 189));
        lblUsername.setText("janedoe12345");
        lblUsername.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblUsernameMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblUsernameMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblUsernameMouseExited(evt);
            }
        });
        jPanel1.add(lblUsername);
        lblUsername.setBounds(100, 60, 460, 20);

        btnExit.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnExit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/librarymanagementsystem/resources/icoExitD.png"))); // NOI18N
        btnExit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnExitMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnExitMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnExitMouseExited(evt);
            }
        });
        jPanel1.add(btnExit);
        btnExit.setBounds(1100, 10, 40, 40);

        jPanel2.setBackground(new java.awt.Color(10, 13, 28));

        lblBookNauthor.setFont(new java.awt.Font("Segoe UI Semilight", 0, 24)); // NOI18N
        lblBookNauthor.setForeground(new java.awt.Color(218, 219, 189));
        lblBookNauthor.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblBookNauthor.setText("jLabel1");

        lblISBN.setFont(new java.awt.Font("Segoe UI Semilight", 0, 18)); // NOI18N
        lblISBN.setForeground(new java.awt.Color(218, 219, 189));
        lblISBN.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblISBN.setText("jLabel1");

        lblBookStat.setFont(new java.awt.Font("Segoe UI Semilight", 0, 18)); // NOI18N
        lblBookStat.setForeground(new java.awt.Color(218, 219, 189));
        lblBookStat.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblBookStat.setText("jLabel1");

        btnGoback.setBackground(new java.awt.Color(218, 219, 189));
        btnGoback.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnGoback.setForeground(new java.awt.Color(10, 13, 28));
        btnGoback.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnGoback.setText("Go back");
        btnGoback.setOpaque(true);
        btnGoback.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnGobackMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnGobackMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnGobackMouseExited(evt);
            }
        });

        imgBook.setMaximumSize(new java.awt.Dimension(260, 350));
        imgBook.setMinimumSize(new java.awt.Dimension(260, 350));
        imgBook.setPreferredSize(new java.awt.Dimension(260, 350));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(103, 103, 103)
                .addComponent(imgBook, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(61, 61, 61)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnGoback, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblBookNauthor)
                    .addComponent(lblISBN)
                    .addComponent(lblBookStat))
                .addContainerGap(625, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(125, 125, 125)
                        .addComponent(lblBookNauthor)
                        .addGap(22, 22, 22)
                        .addComponent(lblISBN)
                        .addGap(33, 33, 33)
                        .addComponent(lblBookStat)
                        .addGap(45, 45, 45)
                        .addComponent(btnGoback, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(67, 67, 67)
                        .addComponent(imgBook, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(109, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 1151, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnUserMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnUserMouseEntered
        // TODO add your handling code here:
        userProfHover();
    }//GEN-LAST:event_btnUserMouseEntered

    private void btnUserMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnUserMouseExited
        // TODO add your handling code here:
        userProfExit();
    }//GEN-LAST:event_btnUserMouseExited

    private void lblURnameMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblURnameMouseEntered
        // TODO add your handling code here:
        userProfHover();
    }//GEN-LAST:event_lblURnameMouseEntered

    private void lblURnameMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblURnameMouseExited
        // TODO add your handling code here:
        userProfExit();
    }//GEN-LAST:event_lblURnameMouseExited

    private void lblUsernameMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblUsernameMouseEntered
        // TODO add your handling code here:
        userProfHover();
    }//GEN-LAST:event_lblUsernameMouseEntered

    private void lblUsernameMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblUsernameMouseExited
        // TODO add your handling code here:
        userProfExit();
    }//GEN-LAST:event_lblUsernameMouseExited

    private void btnExitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnExitMouseClicked
        // TODO add your handling code here:
        int res = JOptionPane.showConfirmDialog(null, "Are you sure you want to Logout?", "Logout?", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);
        if (res == 0) {
            login lf = new login();
            this.dispose();
            lf.show();
        }
    }//GEN-LAST:event_btnExitMouseClicked

    private void btnExitMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnExitMouseEntered
        // TODO add your handling code here:
        exitIconL.getImage().flush();
        btnExit.setIcon(exitIconL);
    }//GEN-LAST:event_btnExitMouseEntered

    private void btnExitMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnExitMouseExited
        // TODO add your handling code here:
        exitIconL.getImage().flush();
        btnExit.setIcon(exitIconD);
    }//GEN-LAST:event_btnExitMouseExited

    private void btnGobackMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnGobackMouseClicked
        // TODO add your handling code here:
        dashboard df = new dashboard(uname, user, utype);
        df.show();
        this.dispose();
    }//GEN-LAST:event_btnGobackMouseClicked

    private void btnGobackMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnGobackMouseEntered
        // TODO add your handling code here:
        Font boldFont = new Font(btnGoback.getFont().getName(), Font.PLAIN, btnGoback.getFont().getSize());
        btnGoback.setFont(boldFont);

        btnGoback.setBackground(new Color(240, 240, 228));
    }//GEN-LAST:event_btnGobackMouseEntered

    private void btnGobackMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnGobackMouseExited
        // TODO add your handling code here:
        Font boldFont = new Font(btnGoback.getFont().getName(), Font.PLAIN, btnGoback.getFont().getSize());
        btnGoback.setFont(boldFont);

        btnGoback.setBackground(new Color(218, 219, 189));
    }//GEN-LAST:event_btnGobackMouseExited

    private void lblUsernameMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblUsernameMouseClicked
        // TODO add your handling code here:
        userProf();
    }//GEN-LAST:event_lblUsernameMouseClicked

    private void lblURnameMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblURnameMouseClicked
        // TODO add your handling code here:
        userProf();
    }//GEN-LAST:event_lblURnameMouseClicked

    private void btnUserMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnUserMouseClicked
        // TODO add your handling code here:
        userProf();
    }//GEN-LAST:event_btnUserMouseClicked

    static BufferedImage bi;

    public static BufferedImage scaleImage(int w, int h, BufferedImage img) throws Exception {
        bi = new BufferedImage(w, h, BufferedImage.TRANSLUCENT);
        Graphics2D g2d = (Graphics2D) bi.createGraphics();
        g2d.setRenderingHint(RenderingHints.KEY_ANTIALIASING, RenderingHints.VALUE_ANTIALIAS_ON);
        g2d.addRenderingHints(new RenderingHints(RenderingHints.KEY_RENDERING, RenderingHints.VALUE_RENDER_QUALITY));
        g2d.drawImage(img, 0, 0, w, h, null);
        g2d.dispose();
        return bi;
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(bookSearchResult.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(bookSearchResult.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(bookSearchResult.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(bookSearchResult.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new bookSearchResult().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel btnExit;
    private javax.swing.JLabel btnGoback;
    private javax.swing.JLabel btnUser;
    private javax.swing.JLabel imgBook;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel lblBookNauthor;
    private javax.swing.JLabel lblBookStat;
    private javax.swing.JLabel lblISBN;
    private javax.swing.JLabel lblURname;
    private javax.swing.JLabel lblUsername;
    // End of variables declaration//GEN-END:variables
}
