/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package librarymanagementsystem;

import java.awt.Color;
import java.awt.Font;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author Charith
 */
public class dashboard extends javax.swing.JFrame {

    /**
     * Creates new form dashboard
     * @param user
     * @param utype
     */
    
    String uname = "";
    String user = "";
    String utype = "";
    
    Connection conn = null;
    
    public dashboard() {
        initComponents();
        lblTmp.requestFocus();
    }
    
    public dashboard(String uname, String user,String utype) {
        initComponents();
        lblTmp.requestFocus();
        this.uname = uname;
        this.user = user;
        this.utype = utype;
        userProfDet();
        if(utype.equals("member"))
        {
            btnGoback.hide();
        }
    }                                    

    void userProf()
    {
        userProfile uf = new userProfile(uname, user, utype);
        uf.show();
        this.dispose();
    }
    
    private void userProfDet()
    {
        lblURname.setText(uname);
        lblUsername.setText(user);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelMain = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        btnUser = new javax.swing.JLabel();
        lblURname = new javax.swing.JLabel();
        lblUsername = new javax.swing.JLabel();
        btnExit = new javax.swing.JLabel();
        pnlMember = new javax.swing.JPanel();
        txtSearch = new javax.swing.JTextField();
        lblTmp = new javax.swing.JLabel();
        btnSearch = new javax.swing.JLabel();
        btnGoback = new javax.swing.JLabel();
        btnClear = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1151, 657));
        setUndecorated(true);
        setPreferredSize(new java.awt.Dimension(1151, 657));
        setResizable(false);
        setSize(new java.awt.Dimension(1151, 657));

        jPanelMain.setBackground(new java.awt.Color(10, 13, 28));
        jPanelMain.setForeground(new java.awt.Color(218, 219, 189));
        jPanelMain.setPreferredSize(new java.awt.Dimension(1151, 657));

        jPanel1.setBackground(new java.awt.Color(10, 13, 28));
        jPanel1.setLayout(null);

        btnUser.setIcon(new javax.swing.ImageIcon(getClass().getResource("/librarymanagementsystem/resources/profIco.png"))); // NOI18N
        btnUser.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnUserMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnUserMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnUserMouseExited(evt);
            }
        });
        jPanel1.add(btnUser);
        btnUser.setBounds(20, 20, 78, 78);

        lblURname.setFont(new java.awt.Font("Segoe UI Semilight", 0, 18)); // NOI18N
        lblURname.setForeground(new java.awt.Color(218, 219, 189));
        lblURname.setText("Jane Doe");
        lblURname.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblURnameMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblURnameMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblURnameMouseExited(evt);
            }
        });
        jPanel1.add(lblURname);
        lblURname.setBounds(100, 40, 580, 25);

        lblUsername.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N
        lblUsername.setForeground(new java.awt.Color(218, 219, 189));
        lblUsername.setText("janedoe12345");
        lblUsername.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblUsernameMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblUsernameMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblUsernameMouseExited(evt);
            }
        });
        jPanel1.add(lblUsername);
        lblUsername.setBounds(100, 60, 490, 20);

        btnExit.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnExit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/librarymanagementsystem/resources/icoExitD.png"))); // NOI18N
        btnExit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnExitMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnExitMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnExitMouseExited(evt);
            }
        });
        jPanel1.add(btnExit);
        btnExit.setBounds(1100, 10, 40, 40);

        pnlMember.setBackground(new java.awt.Color(10, 13, 28));
        pnlMember.setToolTipText("search a book with ISBN number");
        pnlMember.setLayout(null);

        txtSearch.setBackground(new java.awt.Color(10, 13, 28));
        txtSearch.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txtSearch.setForeground(new java.awt.Color(218, 219, 189));
        txtSearch.setText("search");
        txtSearch.setToolTipText("search a book with ISBN number");
        txtSearch.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(218, 219, 189), 1, true));
        txtSearch.setMaximumSize(new java.awt.Dimension(90, 27));
        txtSearch.setMinimumSize(new java.awt.Dimension(90, 27));
        txtSearch.setPreferredSize(new java.awt.Dimension(90, 27));
        txtSearch.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtSearchFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtSearchFocusLost(evt);
            }
        });
        txtSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSearchActionPerformed(evt);
            }
        });
        pnlMember.add(txtSearch);
        txtSearch.setBounds(344, 171, 451, 42);
        pnlMember.add(lblTmp);
        lblTmp.setBounds(10, 35, 24, 24);

        btnSearch.setBackground(new java.awt.Color(218, 219, 189));
        btnSearch.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnSearch.setForeground(new java.awt.Color(10, 13, 28));
        btnSearch.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnSearch.setText("Search");
        btnSearch.setOpaque(true);
        btnSearch.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnSearchMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnSearchMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnSearchMouseExited(evt);
            }
        });
        pnlMember.add(btnSearch);
        btnSearch.setBounds(454, 231, 102, 29);

        btnGoback.setBackground(new java.awt.Color(218, 219, 189));
        btnGoback.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnGoback.setForeground(new java.awt.Color(10, 13, 28));
        btnGoback.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnGoback.setText("Go back");
        btnGoback.setOpaque(true);
        btnGoback.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnGobackMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnGobackMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnGobackMouseExited(evt);
            }
        });
        pnlMember.add(btnGoback);
        btnGoback.setBounds(1010, 470, 102, 29);

        btnClear.setBackground(new java.awt.Color(218, 219, 189));
        btnClear.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnClear.setForeground(new java.awt.Color(10, 13, 28));
        btnClear.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnClear.setText("Clear");
        btnClear.setOpaque(true);
        btnClear.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnClearMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnClearMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnClearMouseExited(evt);
            }
        });
        pnlMember.add(btnClear);
        btnClear.setBounds(583, 231, 102, 29);

        javax.swing.GroupLayout jPanelMainLayout = new javax.swing.GroupLayout(jPanelMain);
        jPanelMain.setLayout(jPanelMainLayout);
        jPanelMainLayout.setHorizontalGroup(
            jPanelMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(pnlMember, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanelMainLayout.setVerticalGroup(
            jPanelMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelMainLayout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(pnlMember, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelMain, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelMain, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnExitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnExitMouseClicked
        // TODO add your handling code here:
        int res = JOptionPane.showConfirmDialog(null,"Are you sure you want to Logout?","Logout?",JOptionPane.YES_NO_OPTION,JOptionPane.QUESTION_MESSAGE);
        if(res==0){
            login lf = new login();
            this.dispose();
            lf.show();
        }
    }//GEN-LAST:event_btnExitMouseClicked

    
    String exitIconLPath = "src\\librarymanagementsystem\\resources\\icoExitL.png";
    ImageIcon exitIconL = new ImageIcon(exitIconLPath);
    
    String exitIconDPath = "src\\librarymanagementsystem\\resources\\icoExitD.png";
    ImageIcon exitIconD = new ImageIcon(exitIconDPath);
    
    private void btnExitMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnExitMouseEntered
        // TODO add your handling code here:
        exitIconL.getImage().flush();
        btnExit.setIcon(exitIconL);
    }//GEN-LAST:event_btnExitMouseEntered

    private void btnExitMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnExitMouseExited
        // TODO add your handling code here:
        exitIconL.getImage().flush();
        btnExit.setIcon(exitIconD);
    }//GEN-LAST:event_btnExitMouseExited

    String proIcoLPath = "src\\librarymanagementsystem\\resources\\proIcoL.png";
    ImageIcon proIcoL = new ImageIcon(proIcoLPath);
    
    String proIcoDPath = "src\\librarymanagementsystem\\resources\\profIco.png";
    ImageIcon proIcoD = new ImageIcon(proIcoDPath);
    
    private void btnUserMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnUserMouseEntered
        // TODO add your handling code here:
        userProfHover();
    }//GEN-LAST:event_btnUserMouseEntered

    private void btnUserMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnUserMouseExited
        // TODO add your handling code here:
        userProfExit();
    }//GEN-LAST:event_btnUserMouseExited

    private void txtSearchFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtSearchFocusGained
        // remove placeholder text
        if(txtSearch.getText().equals("search"))
        {
            txtSearch.setText("");
        }
        txtSearch.setForeground(Color.WHITE);
    }//GEN-LAST:event_txtSearchFocusGained

    private void txtSearchFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtSearchFocusLost
        // add placeholder text
        if(txtSearch.getText().equals(""))
        {
            txtSearch.setText("search");
        }
        txtSearch.setForeground(new Color(218, 219, 189));
    }//GEN-LAST:event_txtSearchFocusLost

    private void txtSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSearchActionPerformed
        // TODO add your handling code here:
        if(!txtSearch.getText().equals("search")){
            txtSearch.requestFocus();
        }
    }//GEN-LAST:event_txtSearchActionPerformed

    private void btnSearchMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSearchMouseClicked
        // TODO add your handling code here:
        searchBook();
    }//GEN-LAST:event_btnSearchMouseClicked

    void searchBook()
    {
        try {
            Class.forName("java.sql.Driver");
            conn = DriverManager.getConnection("jdbc:mysql://localhost/librarymanagementsystem?useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC", "root", "");
            if (conn != null) {
                Statement st1 = conn.createStatement();
                String selQueBook = "SELECT * FROM book WHERE ISBNnumber='" + txtSearch.getText() + "'";
                ResultSet rs1 = st1.executeQuery(selQueBook);
                if (rs1.next()) {
                    String isbn = rs1.getString("ISBNnumber");
                    String bookName = rs1.getString("bookName");
                    String bookAuthor = rs1.getString ("authorName");
                    String currentAv = rs1.getString ("currentAvailability");
                    
                    new bookSearchResult(uname,user,utype,isbn,bookName,bookAuthor,currentAv).setVisible(true);
                    this.dispose();
                }
                else {
                    JOptionPane.showMessageDialog(null, "Book does not exist....","ERROR!!!",JOptionPane.ERROR_MESSAGE);
                    txtSearch.setText("search");
                    lblTmp.requestFocus();
                }
                conn.close();
            }
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, "Database connectivity is NOT successful...." + "\n" + ex);
        }
    }
    
    private void btnSearchMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSearchMouseEntered
        // change button color (highlighted)
        Font boldFont = new Font(btnSearch.getFont().getName(),Font.PLAIN,btnSearch.getFont().getSize());
        btnSearch.setFont(boldFont);

        btnSearch.setBackground(new Color(240, 240, 228));
    }//GEN-LAST:event_btnSearchMouseEntered

    private void btnSearchMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSearchMouseExited
        // change button color (highlight removed)
        Font boldFont = new Font(btnSearch.getFont().getName(),Font.PLAIN,btnSearch.getFont().getSize());
        btnSearch.setFont(boldFont);

        btnSearch.setBackground(new Color(218, 219, 189));
    }//GEN-LAST:event_btnSearchMouseExited

    private void btnClearMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnClearMouseClicked
        // TODO add your handling code here:
        txtSearch.setText("search");
        lblTmp.requestFocus();
    }//GEN-LAST:event_btnClearMouseClicked

    private void btnClearMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnClearMouseEntered
        // TODO add your handling code here:
        Font boldFont = new Font(btnClear.getFont().getName(),Font.PLAIN,btnClear.getFont().getSize());
        btnClear.setFont(boldFont);

        btnClear.setBackground(new Color(240, 240, 228));
    }//GEN-LAST:event_btnClearMouseEntered

    private void btnClearMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnClearMouseExited
        // TODO add your handling code here:
        Font boldFont = new Font(btnClear.getFont().getName(),Font.PLAIN,btnClear.getFont().getSize());
        btnClear.setFont(boldFont);

        btnClear.setBackground(new Color(218, 219, 189));
    }//GEN-LAST:event_btnClearMouseExited

    void userProfHover()
    {
        lblURname.setForeground(Color.white);
        lblUsername.setForeground(Color.white);
        proIcoL.getImage().flush();
        btnUser.setIcon(proIcoL);
    }
    
    void userProfExit()
    {
        lblURname.setForeground(new Color(218, 219, 189));
        lblUsername.setForeground(new Color(218, 219, 189));
        proIcoD.getImage().flush();
        btnUser.setIcon(proIcoD);
    }
    
    private void lblURnameMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblURnameMouseEntered
        // TODO add your handling code here:
        userProfHover();
    }//GEN-LAST:event_lblURnameMouseEntered

    private void lblUsernameMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblUsernameMouseEntered
        // TODO add your handling code here:
        userProfHover();
    }//GEN-LAST:event_lblUsernameMouseEntered

    private void lblURnameMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblURnameMouseExited
        // TODO add your handling code here:
        userProfExit();
    }//GEN-LAST:event_lblURnameMouseExited

    private void lblUsernameMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblUsernameMouseExited
        // TODO add your handling code here:
        userProfExit();
    }//GEN-LAST:event_lblUsernameMouseExited

    private void btnGobackMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnGobackMouseClicked
        // TODO add your handling code here:
        new admindashboard(uname,user,utype).setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnGobackMouseClicked

    private void btnGobackMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnGobackMouseEntered
        // TODO add your handling code here:
        Font boldFont = new Font(btnGoback.getFont().getName(),Font.PLAIN,btnGoback.getFont().getSize());
        btnGoback.setFont(boldFont);

        btnGoback.setBackground(new Color(240, 240, 228));
    }//GEN-LAST:event_btnGobackMouseEntered

    private void btnGobackMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnGobackMouseExited
        // TODO add your handling code here:
        Font boldFont = new Font(btnGoback.getFont().getName(),Font.PLAIN,btnGoback.getFont().getSize());
        btnGoback.setFont(boldFont);

        btnGoback.setBackground(new Color(218, 219, 189));
    }//GEN-LAST:event_btnGobackMouseExited

    private void lblURnameMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblURnameMouseClicked
        // TODO add your handling code here:
        userProf();
    }//GEN-LAST:event_lblURnameMouseClicked

    private void lblUsernameMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblUsernameMouseClicked
        // TODO add your handling code here:
        userProf();
    }//GEN-LAST:event_lblUsernameMouseClicked

    private void btnUserMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnUserMouseClicked
        // TODO add your handling code here:
        userProf();
    }//GEN-LAST:event_btnUserMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new dashboard().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel btnClear;
    private javax.swing.JLabel btnExit;
    private javax.swing.JLabel btnGoback;
    private javax.swing.JLabel btnSearch;
    private javax.swing.JLabel btnUser;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanelMain;
    private javax.swing.JLabel lblTmp;
    private javax.swing.JLabel lblURname;
    private javax.swing.JLabel lblUsername;
    private javax.swing.JPanel pnlMember;
    private javax.swing.JTextField txtSearch;
    // End of variables declaration//GEN-END:variables
}
