/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package librarymanagementsystem;

import java.awt.Color;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author Charith
 */
public class returnBook extends javax.swing.JFrame {

    /**
     * Creates new form bookSearchResult
     */
    String uname = "";
    String user = "";
    String utype = "";
    String isbn = "";
    String bookName = "";
    String bookAuthor = "";
    String currentAv = "";
    
    String member = "";
    String memberUsername = "";
    String bookToReturn = "No";
    String dateToReturn = "Yes";
    
    Connection conn = null;
    
    public returnBook() {
        initComponents();
    }

    returnBook(String uname, String user, String utype) {
        initComponents();
        this.uname = uname;
        this.user = user;
        this.utype = utype;
        userProfDet();
        labelHide();
    }
    
    private void userProfDet()
    {
        lblURname.setText(uname);
        lblUsername.setText(user);
    }
    
    private void labelHide()
    {
        lblBookNauthor.setVisible(false);
        lblISBN.setVisible(false);
        lblBookStat.setVisible(false);
        lblRetunDate.setVisible(false);
        btnReturn.setVisible(false);
        btnSearch.setVisible(true);
        btnClear.setVisible(true);
        txtMember.setVisible(true);
        btnReturn.setVisible(false);
        txtMember.setText("member NIC number");
        lblTemp.requestFocus();
    }
    
    private void labelShow()
    {
        lblBookNauthor.setVisible(true);
        lblISBN.setVisible(true);
        lblBookStat.setVisible(true);
        lblRetunDate.setVisible(true);
        btnReturn.setVisible(true);
        btnSearch.setVisible(false);
        btnClear.setVisible(false);
        txtMember.setVisible(true);
        btnReturn.setVisible(true);
    }


    String exitIconLPath = "src\\librarymanagementsystem\\resources\\icoExitL.png";
    ImageIcon exitIconL = new ImageIcon(exitIconLPath);
    
    String exitIconDPath = "src\\librarymanagementsystem\\resources\\icoExitD.png";
    ImageIcon exitIconD = new ImageIcon(exitIconDPath);
    
    String proIcoLPath = "src\\librarymanagementsystem\\resources\\proIcoL.png";
    ImageIcon proIcoL = new ImageIcon(proIcoLPath);
    
    String proIcoDPath = "src\\librarymanagementsystem\\resources\\profIco.png";
    ImageIcon proIcoD = new ImageIcon(proIcoDPath);
    
    
    void userProfHover()
    {
        lblURname.setForeground(Color.white);
        lblUsername.setForeground(Color.white);
        proIcoL.getImage().flush();
        btnUser.setIcon(proIcoL);
    }
    
    void userProfExit()
    {
        lblURname.setForeground(new Color(218, 219, 189));
        lblUsername.setForeground(new Color(218, 219, 189));
        proIcoD.getImage().flush();
        btnUser.setIcon(proIcoD);
    }
    
    private void bookDetails()
    {
        lblBookNauthor.setText(bookName + " - " + bookAuthor);
        lblISBN.setText("ISBN: " + isbn);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btnUser = new javax.swing.JLabel();
        lblURname = new javax.swing.JLabel();
        lblUsername = new javax.swing.JLabel();
        btnExit = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        lblBookNauthor = new javax.swing.JLabel();
        lblISBN = new javax.swing.JLabel();
        lblBookStat = new javax.swing.JLabel();
        btnReturn = new javax.swing.JLabel();
        btnGoback = new javax.swing.JLabel();
        btnSearch = new javax.swing.JLabel();
        btnClear = new javax.swing.JLabel();
        lblTemp = new javax.swing.JLabel();
        txtMember = new javax.swing.JTextField();
        lblRetunDate = new javax.swing.JLabel();
        imgBook = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1151, 657));
        setUndecorated(true);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(10, 13, 28));
        jPanel1.setLayout(null);

        btnUser.setIcon(new javax.swing.ImageIcon(getClass().getResource("/librarymanagementsystem/resources/profIco.png"))); // NOI18N
        btnUser.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnUserMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnUserMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnUserMouseExited(evt);
            }
        });
        jPanel1.add(btnUser);
        btnUser.setBounds(20, 20, 78, 78);

        lblURname.setFont(new java.awt.Font("Segoe UI Semilight", 0, 18)); // NOI18N
        lblURname.setForeground(new java.awt.Color(218, 219, 189));
        lblURname.setText("Jane Doe");
        lblURname.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblURnameMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblURnameMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblURnameMouseExited(evt);
            }
        });
        jPanel1.add(lblURname);
        lblURname.setBounds(100, 40, 600, 25);

        lblUsername.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N
        lblUsername.setForeground(new java.awt.Color(218, 219, 189));
        lblUsername.setText("janedoe12345");
        lblUsername.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblUsernameMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblUsernameMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblUsernameMouseExited(evt);
            }
        });
        jPanel1.add(lblUsername);
        lblUsername.setBounds(100, 60, 460, 20);

        btnExit.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnExit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/librarymanagementsystem/resources/icoExitD.png"))); // NOI18N
        btnExit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnExitMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnExitMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnExitMouseExited(evt);
            }
        });
        jPanel1.add(btnExit);
        btnExit.setBounds(1100, 10, 40, 40);

        jPanel2.setBackground(new java.awt.Color(10, 13, 28));

        lblBookNauthor.setFont(new java.awt.Font("Segoe UI Semilight", 0, 24)); // NOI18N
        lblBookNauthor.setForeground(new java.awt.Color(218, 219, 189));
        lblBookNauthor.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblBookNauthor.setText("Member does not have a book to return");

        lblISBN.setFont(new java.awt.Font("Segoe UI Semilight", 0, 18)); // NOI18N
        lblISBN.setForeground(new java.awt.Color(218, 219, 189));
        lblISBN.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblISBN.setText(" ");

        lblBookStat.setFont(new java.awt.Font("Segoe UI Semilight", 0, 16)); // NOI18N
        lblBookStat.setForeground(new java.awt.Color(218, 219, 189));
        lblBookStat.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblBookStat.setText("Book to return");

        btnReturn.setBackground(new java.awt.Color(218, 219, 189));
        btnReturn.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnReturn.setForeground(new java.awt.Color(10, 13, 28));
        btnReturn.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnReturn.setText("Return book");
        btnReturn.setOpaque(true);
        btnReturn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnReturnMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnReturnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnReturnMouseExited(evt);
            }
        });

        btnGoback.setBackground(new java.awt.Color(218, 219, 189));
        btnGoback.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnGoback.setForeground(new java.awt.Color(10, 13, 28));
        btnGoback.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnGoback.setText("Go back");
        btnGoback.setOpaque(true);
        btnGoback.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnGobackMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnGobackMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnGobackMouseExited(evt);
            }
        });

        btnSearch.setBackground(new java.awt.Color(218, 219, 189));
        btnSearch.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnSearch.setForeground(new java.awt.Color(10, 13, 28));
        btnSearch.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnSearch.setText("Search");
        btnSearch.setOpaque(true);
        btnSearch.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnSearchMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnSearchMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnSearchMouseExited(evt);
            }
        });

        btnClear.setBackground(new java.awt.Color(218, 219, 189));
        btnClear.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnClear.setForeground(new java.awt.Color(10, 13, 28));
        btnClear.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnClear.setText("Clear");
        btnClear.setOpaque(true);
        btnClear.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnClearMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnClearMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnClearMouseExited(evt);
            }
        });

        txtMember.setBackground(new java.awt.Color(10, 13, 28));
        txtMember.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txtMember.setForeground(new java.awt.Color(218, 219, 189));
        txtMember.setText("member NIC number");
        txtMember.setToolTipText("Search a member with NIC number");
        txtMember.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(218, 219, 189), 1, true));
        txtMember.setMaximumSize(new java.awt.Dimension(90, 27));
        txtMember.setMinimumSize(new java.awt.Dimension(90, 27));
        txtMember.setPreferredSize(new java.awt.Dimension(90, 27));
        txtMember.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtMemberFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtMemberFocusLost(evt);
            }
        });
        txtMember.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtMemberActionPerformed(evt);
            }
        });

        lblRetunDate.setFont(new java.awt.Font("Segoe UI Semilight", 0, 18)); // NOI18N
        lblRetunDate.setForeground(new java.awt.Color(218, 219, 189));
        lblRetunDate.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblRetunDate.setText(" ");

        imgBook.setMaximumSize(new java.awt.Dimension(260, 350));
        imgBook.setMinimumSize(new java.awt.Dimension(260, 350));
        imgBook.setPreferredSize(new java.awt.Dimension(260, 350));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnGoback, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(85, 85, 85)
                .addComponent(imgBook, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(74, 74, 74)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnReturn, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(txtMember, javax.swing.GroupLayout.PREFERRED_SIZE, 385, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(79, 79, 79)
                                .addComponent(lblTemp, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(lblRetunDate)
                            .addComponent(lblISBN)
                            .addComponent(lblBookNauthor)
                            .addComponent(lblBookStat))
                        .addContainerGap(239, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(27, 27, 27)
                        .addComponent(btnClear, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(431, 431, 431))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(78, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtMember, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblTemp, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnClear, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(31, 31, 31)
                        .addComponent(lblBookStat)
                        .addGap(18, 18, 18)
                        .addComponent(lblBookNauthor)
                        .addGap(27, 27, 27)
                        .addComponent(lblISBN)
                        .addGap(26, 26, 26)
                        .addComponent(lblRetunDate)
                        .addGap(18, 18, 18)
                        .addComponent(btnReturn, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(50, 50, 50)
                        .addComponent(btnGoback, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addComponent(imgBook, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(25, 25, 25))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 1151, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnUserMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnUserMouseEntered
        // TODO add your handling code here:
        userProfHover();
    }//GEN-LAST:event_btnUserMouseEntered

    private void btnUserMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnUserMouseExited
        // TODO add your handling code here:
        userProfExit();
    }//GEN-LAST:event_btnUserMouseExited

    private void lblURnameMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblURnameMouseEntered
        // TODO add your handling code here:
        userProfHover();
    }//GEN-LAST:event_lblURnameMouseEntered

    private void lblURnameMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblURnameMouseExited
        // TODO add your handling code here:
        userProfExit();
    }//GEN-LAST:event_lblURnameMouseExited

    private void lblUsernameMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblUsernameMouseEntered
        // TODO add your handling code here:
        userProfHover();
    }//GEN-LAST:event_lblUsernameMouseEntered

    private void lblUsernameMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblUsernameMouseExited
        // TODO add your handling code here:
        userProfExit();
    }//GEN-LAST:event_lblUsernameMouseExited

    private void btnExitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnExitMouseClicked
        // TODO add your handling code here:
        int res = JOptionPane.showConfirmDialog(null,"Are you sure you want to Logout?","Logout?",JOptionPane.YES_NO_OPTION,JOptionPane.QUESTION_MESSAGE);
        if(res==0){
            login lf = new login();
            this.dispose();
            lf.show();
        }
    }//GEN-LAST:event_btnExitMouseClicked

    private void btnExitMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnExitMouseEntered
        // TODO add your handling code here:
        exitIconL.getImage().flush();
        btnExit.setIcon(exitIconL);
    }//GEN-LAST:event_btnExitMouseEntered

    private void btnExitMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnExitMouseExited
        // TODO add your handling code here:
        exitIconL.getImage().flush();
        btnExit.setIcon(exitIconD);
    }//GEN-LAST:event_btnExitMouseExited

    private void btnReturnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnReturnMouseClicked
        // TODO add your handling code here:
        
        if(!("".equals(memberUsername)) && "Yes".equals(bookToReturn))
        {
            try {
                Class.forName("java.sql.Driver");
                conn = DriverManager.getConnection("jdbc:mysql://localhost/librarymanagementsystem?useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC", "root", "");
                int resdel = JOptionPane.showConfirmDialog(null, "Return book with ISBN " + isbn + " from the member "+ member +"???", "Confirm to Return?", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);
                if (resdel == 0) {
                    if (conn != null) {
                        String addBookQ = "UPDATE issue SET bookReturned='Yes' WHERE mUsername=? AND ISBNnumber=?";
                        PreparedStatement ps = conn.prepareCall(addBookQ);
                        ps.setString(1, memberUsername);
                        ps.setString(2, isbn);
                        ps.execute();
                        JOptionPane.showMessageDialog(this, "Book " + isbn + " was Successfully reuturned by the member with nic "+member+"!", "Returned!", JOptionPane.INFORMATION_MESSAGE);
                        ps.close();
                        
                        
                        //update member table bookToReturn
                        String upQue = "UPDATE member SET bookToReturn='No' WHERE nicNumber=?";
                        ps = conn.prepareCall(upQue);
                        ps.setString(1, member);
                        ps.executeUpdate();
                        ps.close();
                        
                        //update book table currentAv
                        upQue = "UPDATE book SET currentAvailability='Available' WHERE ISBNnumber=?";
                        ps = conn.prepareCall(upQue);
                        ps.setString(1, isbn);
                        ps.executeUpdate();
                        ps.close();
                        
                        
                        conn.close();
                        labelHide();
                        memberUsername = "";
                        currentAv = "";
                        bookToReturn = "No";
                        member = "";
                        isbn = "";
                        bookName = "";
                        bookAuthor = "";
                        imgBook.setIcon(null);
                    }
                }
            } catch (Exception ex) {
                JOptionPane.showMessageDialog(null, "Database connectivity is NOT successful...." + "\n" + ex);
            }
        }
        else
        {
            JOptionPane.showMessageDialog(this, "Member with NIC no. "+txtMember.getText()+" has no book to return!" + "\n");
            txtMember.requestFocus();
        }
    }//GEN-LAST:event_btnReturnMouseClicked

    void getMemberDet()
    {
        member = txtMember.getText();
        try {
            Class.forName("java.sql.Driver");
            conn = DriverManager.getConnection("jdbc:mysql://localhost/librarymanagementsystem?useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC", "root", "");
            if (conn != null) {
                Statement st2 = conn.createStatement();
                String selQueMem = "SELECT * FROM member WHERE nicNumber='" + txtMember.getText() + "'";
                ResultSet rs2 = st2.executeQuery(selQueMem);
                if (rs2.next()) {
                    memberUsername = rs2.getString("mUsername");
                    bookToReturn = rs2.getString("bookToReturn");
                }
                conn.close();
            }
            else {
                JOptionPane.showMessageDialog(this, "Member with NIC no. "+txtMember.getText()+" is not in the system!" + "\n");
                txtMember.requestFocus();
            }
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, "Database connectivity is NOT successful...." + "\n" + ex);
        }
    }
    
    private void btnReturnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnReturnMouseEntered
        // TODO add your handling code here:
        btnReturn.setBackground(new Color(240, 240, 228));
    }//GEN-LAST:event_btnReturnMouseEntered

    private void btnReturnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnReturnMouseExited
        // TODO add your handling code here:
        btnReturn.setBackground(new Color(218, 219, 189));
    }//GEN-LAST:event_btnReturnMouseExited

    private void btnGobackMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnGobackMouseClicked
        // TODO add your handling code here:
        admindashboard df = new admindashboard(uname, user, utype);
        df.show();
        this.dispose();
    }//GEN-LAST:event_btnGobackMouseClicked

    private void btnGobackMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnGobackMouseEntered
        // TODO add your handling code here:
        btnGoback.setBackground(new Color(240, 240, 228));
    }//GEN-LAST:event_btnGobackMouseEntered

    private void btnGobackMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnGobackMouseExited
        // TODO add your handling code here:
        btnGoback.setBackground(new Color(218, 219, 189));
    }//GEN-LAST:event_btnGobackMouseExited

    void searchBook()
    {
            try {
            Class.forName("java.sql.Driver");
            conn = DriverManager.getConnection("jdbc:mysql://localhost/librarymanagementsystem?useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC", "root", "");
            if (conn != null) {
                Statement st1 = conn.createStatement();
                String selQueBook = "SELECT * FROM book WHERE ISBNnumber='" + isbn + "'";
                ResultSet rs1 = st1.executeQuery(selQueBook);
                if (rs1.next()) {
                    isbn = rs1.getString("ISBNnumber");
                    bookName = rs1.getString("bookName");
                    bookAuthor = rs1.getString ("authorName");
                    currentAv = rs1.getString ("currentAvailability");
                    bookDetails();
                    labelShow();
                }
                else {
                    JOptionPane.showMessageDialog(null, "Book does not exist....","ERROR!!!",JOptionPane.ERROR_MESSAGE);

                }
                conn.close();
                Book bk = new Book();   //creating a object from Book class
                bk.openBookIamge(isbn, imgBook);
                lblTemp.requestFocus();
            }
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, "Database connectivity is NOT successful...." + "\n" + ex);
        }
    }
    
    void issuDetails()
    {
            try {
            Class.forName("java.sql.Driver");
            conn = DriverManager.getConnection("jdbc:mysql://localhost/librarymanagementsystem?useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC", "root", "");
            if (conn != null) {
                Statement st1 = conn.createStatement();
                String selQueBook = "SELECT * FROM issue WHERE mUsername='" + memberUsername + "' AND bookReturned='No'";
                ResultSet rs1 = st1.executeQuery(selQueBook);
                if (rs1.next()) {
                    isbn = rs1.getString("ISBNnumber");
                    dateToReturn = rs1.getString ("dateToReturn");
                    searchBook();
                    labelShow();
                    lblRetunDate.setText("Date to return: " + dateToReturn);
                }
                else {
                    JOptionPane.showMessageDialog(null, "Member with nic "+member+" has no book to return!","No book to return!",JOptionPane.ERROR_MESSAGE);

                }
                conn.close();
                lblTemp.requestFocus();
            }
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, "Database connectivity is NOT successful...." + "\n" + ex);
        }
    }
    
    private void btnSearchMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSearchMouseClicked
        // TODO add your handling code here:
        //get details from issue table
        getMemberDet();
        issuDetails();
    }//GEN-LAST:event_btnSearchMouseClicked

    private void btnSearchMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSearchMouseEntered
        // change button color (highlighted)
        btnSearch.setBackground(new Color(240, 240, 228));
    }//GEN-LAST:event_btnSearchMouseEntered

    private void btnSearchMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSearchMouseExited
        // change button color (highlight removed)
        btnSearch.setBackground(new Color(218, 219, 189));
    }//GEN-LAST:event_btnSearchMouseExited

    private void btnClearMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnClearMouseClicked
        // TODO add your handling code here:
        txtMember.setText("member NIC number");
        lblTemp.requestFocus();
    }//GEN-LAST:event_btnClearMouseClicked

    private void btnClearMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnClearMouseEntered
        // TODO add your handling code here:
        btnClear.setBackground(new Color(240, 240, 228));
    }//GEN-LAST:event_btnClearMouseEntered

    private void btnClearMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnClearMouseExited
        // TODO add your handling code here:
        btnClear.setBackground(new Color(218, 219, 189));
    }//GEN-LAST:event_btnClearMouseExited

    private void txtMemberFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtMemberFocusGained
        // TODO add your handling code here:
        if(txtMember.getText().equals("member NIC number"))
        {
            txtMember.setText("");
        }
        txtMember.setForeground(Color.WHITE);
    }//GEN-LAST:event_txtMemberFocusGained

    private void txtMemberFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtMemberFocusLost
        // TODO add your handling code here:
        if(txtMember.getText().equals(""))
        {
            txtMember.setText("member NIC number");
        }
        txtMember.setForeground(new Color(218, 219, 189));
    }//GEN-LAST:event_txtMemberFocusLost

    private void txtMemberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtMemberActionPerformed
        // TODO add your handling code here:
        getMemberDet();
        issuDetails();
    }//GEN-LAST:event_txtMemberActionPerformed

    private void lblURnameMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblURnameMouseClicked
        // TODO add your handling code here:
        userProf();
    }//GEN-LAST:event_lblURnameMouseClicked

    private void lblUsernameMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblUsernameMouseClicked
        // TODO add your handling code here:
        userProf();
    }//GEN-LAST:event_lblUsernameMouseClicked

    private void btnUserMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnUserMouseClicked
        // TODO add your handling code here:
        userProf();
    }//GEN-LAST:event_btnUserMouseClicked

    void userProf()
    {
        userProfile uf = new userProfile(uname, user, utype);
        uf.show();
        this.dispose();
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(returnBook.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(returnBook.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(returnBook.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(returnBook.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new returnBook().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel btnClear;
    private javax.swing.JLabel btnExit;
    private javax.swing.JLabel btnGoback;
    private javax.swing.JLabel btnReturn;
    private javax.swing.JLabel btnSearch;
    private javax.swing.JLabel btnUser;
    private javax.swing.JLabel imgBook;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel lblBookNauthor;
    private javax.swing.JLabel lblBookStat;
    private javax.swing.JLabel lblISBN;
    private javax.swing.JLabel lblRetunDate;
    private javax.swing.JLabel lblTemp;
    private javax.swing.JLabel lblURname;
    private javax.swing.JLabel lblUsername;
    private javax.swing.JTextField txtMember;
    // End of variables declaration//GEN-END:variables
}
